### ISSUE TITLE
issue docker-compose up

### ISSUE THREAD

**Issue by jujes** [niieani/pydio-docker-compose#1]
**docker-compose up -d**

ERROR: build path ~/pydio-docker-compose/config/letsencrypt either does not exist, is not accessible, or is not a valid URL.

**Comment by niieani** [comment]
Should be fixed, was a wrong path in the .yml.

I'm still working out the bugs (I just pushed this project yesterday).

**Comment by jujes** [comment]
I'm looking a project like this from last month.. :)
Now I have this error:

ERROR: Service "php" mounts volumes from "mysql-socket", which is not the name of a service or container.

Docker version 1.10.2, build c3959b1
docker-compose version 1.6.2, build 4d72027

**Comment by niieani** [comment]
Give me a couple of hours, I'll fix it.

**Comment by jujes** [comment]
great! :+1: 
I'm stay here trying to deploy the project...

**Comment by niieani** [comment]
@jujes can you try now?

**Comment by jujes** [comment]
@niieani wonderful! docker-compose up **successful build** :+1:  but:
1. **PHP extension 'mysql' is not loaded** (when I trie to set up the the installation) 
    if I user docker exec -it mysql bash > service mysql restart
    get: Stopping MariaDB database server: mysqld failed!
           Starting MariaDB database server: mysqld already running.
2. when I try go to my files get: **cannot create root path for repository** (My Files) and **trying to switch to an unknown repository**
3. SSL localhost certificate is not trusted

[http://imgur.com/a/wS2El](url)
Thanks in advance :)

**Comment by niieani** [comment]
1. use mysqli, not mysql (it's an option during installation). If you want to restart mysql, you do it like this: `docker-compose restart mysql`
2. apply step 4 from the README to fix this
3. you can't use LetsEncrypt for localhost certificate. You need a domain name that you purchased to be pointing to the IP you're deploying it on.

**Comment by jujes** [comment]
@niieani I need add chown -R 33:33 ./persistent/data to my docker-compose.yml? or where is located ?

Thanks :)
ps. Sorry I'm learning docker-compose

**Comment by niieani** [comment]
No, execute that command from the terminal in your docker-compose
directory. It's unrelated to docker-compose.

**Comment by jujes** [comment]
@niieani I execute that command form the terminal and get the same issue, please check my video:
https://youtu.be/JW8QrzwQpIs

**Solved** editing /srv/www/conf/**bootstrap_repositories.php**

1 – find this line :
“PATH”  =>  “AJXP_DATA_PATH/personal/AJXP_USER”,
2 – change the default path like this for windows OS:
“PATH”  =>  **"/pydio-data/personal/AJXP_USER",**
REM : always keep “/AJXP_USER” in path

PLUS - I change too **AJXP_DATA_PATH/files** for **"/pydio-data/files"** because it not let me sync whit pydio sync

Following this guide:
https://pydio.com/forum/f/topic/how-to-change-my-files-path/
